name: (level 4 sub) Inter Belt

on:
  workflow_call:
    inputs:
      DOCKER_BUILD_REPO:
        required: true
        type: string
      DOCKER_TARGET_REPO:
        required: false
        default: ''
        type: string
      IMAGE_BASE_NAME:
        required: true
        type: string
      IMAGE_VERSION:
        required: false
        default: ''
        type: string
      ARCH:
        required: true
        type: string
      PR_MODE:
        required: false
        type: boolean
    secrets:
      DOCKER_PASSWORD:
        required: false
      DOCKER_USERNAME:
        required: false
    outputs:
      build:
        description: "Failed build"
        value: ${{ jobs.export_results.outputs.build }}
      push:
        description: "Failed push"
        value: ${{ jobs.export_results.outputs.push }}
      test:
        description: "Failed tests"
        value: ${{ jobs.export_results.outputs.test }}

jobs:
  build-ca:
    name: Build Code Analysis Image
    uses: ./.github/workflows/sub_build.yml
    with:
      DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
      IMAGE_BASE_NAME: nightly-code-analysis
      IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
      DOCKERFILE: code_analysis.dockerfile
      ARCH: ${{ inputs.ARCH }}
  
  build-ad:
    name: Build Active Directory Image
    uses: ./.github/workflows/sub_build.yml
    with:
      DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
      IMAGE_BASE_NAME: nightly-ad
      IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
      DOCKERFILE: ad.dockerfile
      ARCH: ${{ inputs.ARCH }}

  # build-ca3:
  #   name: Build Code Analysis Image 3
  #   uses: ./.github/workflows/sub_build.yml
  #   with:
  #     DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
  #     IMAGE_BASE_NAME: nightly-code-analysis
  #     IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
  #     DOCKERFILE: ./refactor/code_analysis.dockerfile
  #     ARCH: ${{ inputs.ARCH }}

  # build-ca4:
  #   name: Build Code Analysis Image 4
  #   uses: ./.github/workflows/sub_build.yml
  #   with:
  #     DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
  #     IMAGE_BASE_NAME: nightly-code-analysis
  #     IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
  #     DOCKERFILE: ./refactor/code_analysis.dockerfile
  #     ARCH: ${{ inputs.ARCH }}

  # build-ca5:
  #   name: Build Code Analysis Image 5
  #   uses: ./.github/workflows/sub_build.yml
  #   with:
  #     DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
  #     IMAGE_BASE_NAME: nightly-code-analysis
  #     IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
  #     DOCKERFILE: ./refactor/code_analysis.dockerfile
  #     ARCH: ${{ inputs.ARCH }}