name: (level 5 sub) End Belt

on:
  workflow_call:
    inputs:
      DOCKER_BUILD_REPO:
        required: true
        type: string
      DOCKER_TARGET_REPO:
        required: false
        default: ''
        type: string
      IMAGE_BASE_NAME:
        required: true
        type: string
      IMAGE_VERSION:
        required: false
        default: ''
        type: string
      ARCH:
        required: true
        type: string
      PR_MODE:
        required: false
        type: boolean
    secrets:
      DOCKER_PASSWORD:
        required: false
      DOCKER_USERNAME:
        required: false
    outputs:
      build:
        description: "Failed build"
        value: ${{ jobs.export_results.outputs.build }}
      push:
        description: "Failed push"
        value: ${{ jobs.export_results.outputs.push }}
      test:
        description: "Failed tests"
        value: ${{ jobs.export_results.outputs.test }}

jobs:
  build-full:
    name: Build Complete Image
    uses: ./.github/workflows/sub_build.yml
    with:
      DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
      IMAGE_BASE_NAME: nightly-full
      IMAGE_VERSION: ${{ inputs.IMAGE_VERSION }}
      DOCKERFILE: full.dockerfile
      ARCH: ${{ inputs.ARCH }}

  test:
    name: Final tests
    needs:
      - build-full
    uses: ./.github/workflows/sub_test.yml
    with:
      DOCKER_BUILD_REPO: ${{ inputs.DOCKER_BUILD_REPO }}
      IMAGE_BASE_NAME: nightly-full
      ARCH: ${{ inputs.ARCH }}

  cleanup:
    name: Remove dangling images
    needs: test
    runs-on:
      - self-hosted
      - builder
      - ${{ inputs.ARCH }}
    steps:
      - name: Cleanup
        run: docker rmi $(docker images -f "dangling=true" -q)